### ISSUE TITLE
Install fails on Node 4.0.0 and 4.1.1 Mac OS X

### ISSUE THREAD

**Issue by megastef** [bripkens/gcstats.js#1]
```
 npm i gcstats.js

> gcstats.js@1.0.0 install /Users/stefan/sematext/spm-agent-nodejs/node_modules/gcstats.js
> node-gyp rebuild

  CXX(target) Release/obj.target/gcstats/src/gcstats.o
  SOLINK_MODULE(target) Release/gcstats.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/gcstats.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/stefan/sematext/spm-agent-nodejs/node_modules/gcstats.js
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

**Comment by bripkens** [comment]
Works for me with all versions mentioned in [1] on my Mac and also on Travis CI. Sorry, I cannot reproduce the issue, but Googling it turns up many results. Maybe some of them work for you?

[1] https://github.com/bripkens/gcstats.js/blob/master/compatibility.md
